<a href="https://colab.research.google.com/github/btlgs2000/machine_learning_basic/blob/master/numpy_tutorial_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tutorial Numpy

In [ ]:
import numpy as np

## Creazione da una lista

In [ ]:
a = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12], [13,14,15,16,17,18]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [ ]:
rows, cols = a.shape

In [ ]:
cols

6

In [ ]:
a.dtype

dtype('int64')

In [ ]:
# numero di elementi totali
a.size

18

In [ ]:
a.ndim

2

## Indexing

In [ ]:
# singolo elemento
a[0, 2]

3

In [ ]:
a[::2, :]

array([[ 1,  2,  3,  4,  5,  6],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
# righe alterne
a[::2, :]

In [ ]:
# boolean indexing
a > 10

array([[False, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
# Attenzione alla priorità degli operatori logici!
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18])

In [ ]:
a[a>10] = -1

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, -1, -1],
       [-1, -1, -1, -1, -1, -1]])

## Funzioni di creazione

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.linspace(1., 4., 6)

In [ ]:
np.random.random((3, 3))

array([[0.5713664 , 0.95231981, 0.67799247],
       [0.11607323, 0.31741469, 0.56529746],
       [0.07095686, 0.71289906, 0.7068032 ]])

In [ ]:
np.random.normal(loc=10, scale=3, size=(3, 2))

array([[ 8.98576718,  8.38832606],
       [ 8.80426723, 12.35455862],
       [ 7.81017199,  8.87291163]])

## funzioni elementwise

In [ ]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[10, 10], [10, 10]])

In [ ]:
a @ b

array([[30, 30],
       [70, 70]])

## funzioni matriciali

In [ ]:
A = np.array([[1, 1], [2,3]])
B = np.array([[1, 4], [-2,3]])

In [ ]:
# in caso di array con più di due dimensioni vengono trattati come array di matrici
np.matmul(A, B)

In [ ]:
A @ B

In [ ]:
from numpy.linalg import inv

inv(A) @ A

## funzioni di riduzione

In [ ]:
# 2 x 3

a = [
     [1, 2 ,3 ],
     [4, 5, 6]
]

In [ ]:
arr = np.max(a, axis=0); arr

array([4, 5, 6])

In [ ]:
np.max(a)

6

In [ ]:
np.amax(A)

In [ ]:
np.amax(A, axis = 0)

In [ ]:
np.amax(A, axis = 0, keepdims=True)

## cambio di dimensioni

In [ ]:
a = np.array(
    [
     [1, 2, 3],
     [4, 5, 6]
    ]
)

In [ ]:
# gli indici scorrono dall'ultimo al primo a[0,0], a[0,1]...a[1,0], a[1,1]
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.reshape(1, 6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a.reshape(-1)

In [ ]:
a.reshape((2, -1))

In [ ]:
a = np.array([1, 2, 3]).reshape(1, -1, 1)

In [ ]:
a.shape

In [ ]:
a_sq = a.squeeze()

In [ ]:
a_sq.shape

In [ ]:
# trasposta
a = np.array([[1, 1], [2, 2]]); a.T

## Broadcating

https://numpy.org/doc/stable/user/basics.broadcasting.html

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a + 2

array([[3, 4],
       [5, 6]])

In [ ]:
a + np.array([[10], [11]])

array([[11, 12],
       [14, 15]])

In [ ]:
fake_img = np.random.random((3, 5, 5))
fake_img + np.array([1, 2, 3]).reshape(3, 1, 1)

In [ ]:
fake_img + np.array([1, 2, 3, 4, 5])

In [ ]:
fake_img + np.array([1, 2, 3, 4, 5]).reshape(1, -1, 1)

In [ ]:
fake_img + np.array([[1], [2], [3], [4], [5]])

In [ ]:
a = np.random.rand(3, 2, 4)
b = np.random.rand(1, 2, 4)

In [ ]:
a + b

array([[[1.41931429, 1.10600507, 0.90269602, 0.6516676 ],
        [0.17294702, 1.34778976, 1.34125808, 1.33168796]],

       [[1.47661329, 1.48307551, 0.85790419, 1.39998828],
        [0.43635284, 0.90625562, 1.17215203, 0.92629215]],

       [[1.6939882 , 1.77842957, 1.20450453, 1.37658912],
        [0.37358949, 0.90626783, 1.25017913, 1.13792859]]])

## Unione di array

In [ ]:
# unisce array con la stessa forma creando una nuova dimensione

a = np.array([[1, 2], [3, 4]])
b = np.array([[11, 12], [13, 14]])

In [ ]:
np.stack((a, b))

array([[[ 1,  2],
        [ 3,  4]],

       [[11, 12],
        [13, 14]]])

In [ ]:
np.concatenate((a, b), axis=0)

In [ ]:
np.vstack((a, b)).shape

(4, 2)

In [ ]:
a = np.random.rand(4, 5)

In [ ]:
def matrix_power(M, n):
    ''' restituisce M**n
    la moltiplicazione matriciale è scritta in Python
    
    args
    ----
    M (list): dimensioni n x n [[1, 2], [3, 4]]
    n (int): esponente
    '''
    def matrix_multiply(A, B):
        m = len(A) # mumero di righe di A
        n = len(B[0]) # numero di colonne di B
        l = len(A[0]) # numero di colonne di A == numero di righe di B
        res = [[0]*n for _ in range(m)]
        for row in range(m):
            for col in range(n):
                acc = 0
                for i in range(l):
                    acc += A[row][i] * B[i][col]
                res[row][col]= acc

        return res

    power = M
    for _ in range(n-1):
        power = matrix_multiply(power, M)
    return power

def matrix_power_numpy(M, n):
    ''' come sopra ma utilizzando numpy

    args
    ----
    M (np.array): dimensioni n x n
    n (int): esponente
    '''
    power = M
    for _ in range(n-1):
        power = power@M
    return power

In [ ]:
M = np.array([[2, 3], [1, 1]])

In [ ]:
matrix_power(M, 10)

[[98644, 128511], [42837, 55807]]

In [ ]:
matrix_power_numpy(M, 2)

array([[253.6337322 , 247.79477625, 255.91669657, ..., 247.22053629,
        243.4791392 , 252.46142148],
       [251.81865834, 251.53224739, 251.40667711, ..., 253.98696279,
        256.98336577, 253.76670449],
       [251.81867358, 244.79413043, 257.03587695, ..., 252.92877327,
        247.83511462, 249.53888704],
       ...,
       [257.0346591 , 244.3129661 , 259.44034988, ..., 258.15410903,
        253.75463308, 253.75687561],
       [264.39320085, 254.74397319, 264.25641951, ..., 262.35795999,
        260.53569844, 262.61882653],
       [246.20629677, 240.25702424, 254.2822506 , ..., 249.74039318,
        247.99696139, 247.86991096]])

In [ ]:
import time

M = np.random.rand(1_000, 1_000)

start = time.time()
matrix_power(M, 2)
stop = time.time()

print(f'tempo impiegato = {stop-start}')

KeyboardInterrupt: ignored

In [ ]:
import time

M = np.random.rand(1_000, 1_000)

start = time.time()
matrix_power_numpy(M, 2)
stop = time.time()

print(f'tempo impiegato = {stop-start}')

tempo impiegato = 0.06707429885864258


## Esercizi

### 1

In [ ]:
a = np.random.random((5, 5)); a

In [ ]:
rows, cols = a.shape
for i in range(rows):
    for j in range(cols):
        a[i][j] = np.sin(a[i][j])*2 + 4

### 2

In [ ]:
a = np.random.random((5, 5)); a

In [ ]:
rows, cols = a.shape
for i in range(rows):
    for j in range(cols):
        if j == 3:
            a[i][j] += 10

### 3

In [ ]:
a = np.random.random((5, 5)); a

In [ ]:
for i in range(rows):
    for j in range(cols):
            a[i][j] += j

### 4

In [ ]:
a = np.random.random((5, 5)); a

In [ ]:
for i in range(rows):
    for j in range(cols):
            a[i][j] += i + j**2

### 5

In [ ]:
a = np.stack([np.eye(2)*i for i in range(4)]); a

In [ ]:
b = np.array([[1, 2], [3, 4]])

In [ ]:
for i in range(a.shape[0]):
    a[i] = a[i]@b

### 6

In [ ]:
a = np.random.random((5, 5)); a

In [ ]:
rows, cols = a.shape
sums_over_cols = [0]*5
for j in range(cols):
    for i in range(rows):
        sums_over_cols[i] += a[i][j]

sum_ = sum(sums_over_cols) / rows

In [ ]:
sum_

### 7

In [ ]:
a = np.random.random((10, 4))
b = np.random.random((10, 4))

c = np.zeros_like(a)

res = [0]*4

for i in range(10):
    for j in range(4):
        c[i][j] = (a[i][j]-b[i][j])**2

for j in range(4):
    acc = 0
    for i in range(10):
        acc += a[i][j]
    res[j] = acc / 10

In [ ]:
res